server:
  port: 8086

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:h2:mem:mydb
    username: fred
    password: password
    driver-class-name: org.h2.Driver
  spring:
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect




